[build]
  command = "npm run build"
  publish = "public"

# هدایت مسیرهای مشخص شده به سمت اسکریپت relay
[[edge_functions]]
  path = "/api/v1/*"
  function = "relay"

[[edge_functions]]
  path = "/data/*"
  function = "relay"

[[edge_functions]]
  path = "/service/*"
  function = "relay"

# تنظیم هدرهای امنیتی برای عادی جلوه دادن سایت
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Server = "cloudflare" # اضافه کردن هدر جعلی سرور برای گمراه کردن سیستم‌های مانیتورینگ
